version: '3.8'

services:
  bot:
    build: .
    container_name: macacolandia-music-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot.py:/app/bot.py
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PREFIX=${PREFIX}
